refactor: migrate to ESM
haversnail/inquirer-date-prompt pull request #4
Opened 2022-07-15 02:49 UTC by Gopikrishna19

BREAKING CHANGE: This package is now pure ESM. Please use supporting Node.js version to use this package. Or keep using v2.x until you are ready to switch

closes #3

2022-07-19 12:58 UTC, Gopikrishna19 commented
@haversnail hey, can I get a review/merge on this, please? I have an ESM project and want to use this date picker. I couldn't
find a better library than yours. I am using a locally modified copy of yours, but instead, use the package to reduce code redundancy. Please let me know if something has to be changed or anything, I will be happy to get it done :)

2022-07-26 18:09 UTC, haversnail commented
@Gopikrishna19 thanks for picking up this work! Absolutely, let me take a look and see if we can get this merged as soon as possible.

2022-07-26 18:20 UTC, haversnail requested changes
Just need to bump the node version in the GitHub action workflow, but other than that looks good! Thanks again for tackling this. 🙏 Let me know if you would rather me jump in and fix, otherwise I'll keep an eye out for the change.

2022-07-26 18:20 UTC, haversnail commented on .github/workflows/cd.yml
> +  NODE_VERSION: "12.20.0"
I noticed that `semantic-release` was bumped to v19 (and the `git` plugin to v10)... it looks like as of v18, the minimum required version of node is v14.17 (release notes [here](https://github.com/semantic-release/semantic-release/releases/tag/v18.0.0)). Though v12 should be fine for consumers of the package, we'll probably need to make sure that the GitHub action runners are on the latest minor version of 14 so that Semantic Release works correctly:
```
  NODE_VERSION: "14"
```

2022-07-26 18:20 UTC, haversnail commented on package.json
> +    "node": "^12.20.0 || ^14.13.1 || >=16.0.0"
Just curious, any reason for 12.20.0 or 14.13.1 specifically?

2022-08-09 16:04 UTC, haversnail commented
@Gopikrishna19 is this still something you're interested in working on? No worries if not, just let me know and I can see about making the changes.

2022-10-03 10:33 UTC, AhmedBahgat commented
Hello,
I am waiting this PR to be release awhile ago :) 
If there is something I can help with. looking forward to use this change ASAP

2022-10-12 15:23 UTC, closed without merging

2022-10-12 18:54 UTC, haversnail commented
@ABHammad thanks for your patience (and for the nudge)! Released in v3.